apiVersion: v1
kind: Service
metadata:
  name: svc-httpd-6
  labels:
    app: svc-httpd-6
spec:
  type: LoadBalancer
  ports:
    - name: svc-httpd-6
      port: 80
      targetPort: 80
  selector:
    app: deploy-httpd-6
