apiVersion: apps/v1

kind: Deployment

metadata:

  name: deploy-httpd-1

  labels:

    app: deploy-httpd-1

spec:

  replicas: 3

  selector:

    matchLabels:

      app: deploy-httpd-1

  template:

    metadata:

      labels:

        app: deploy-httpd-1

    spec:

      containers:

      - name: httpd

        image: httpd:2.4.54

        ports:

        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-webserver-1
  labels:
    app: webserver-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-1
  template:
    metadata:
      labels:
        app: webserver-1
    spec:
      containers:
      - name: webserver
        image: nginx:1.19
        ports:
        - containerPort: 80
