apiVersion: v1
kind: Service
metadata:
  name: svc-httpd-3
  labels:
    app: svc-httpd-3
spec:
  type: LoadBalancer
  ports:
    - name: svc-httpd-3
      port: 80
      targetPort: 80
  selector:
    app: deploy-httpd-3
