apiVersion: apps/v1

kind: Deployment

metadata:

  name: deploy-httpd-4

  labels:

    app: deploy-httpd-4

spec:

  replicas: 3

  selector:

    matchLabels:

      app: deploy-httpd-4

  template:

    metadata:

      labels:

        app: deploy-httpd-4

    spec:

      containers:

      - name: httpd

        image: httpd:2.4.54

        ports:

        - containerPort: 80
