apiVersion: v1
kind: Service
metadata:
  name: svc-httpd-4
  labels:
    app: svc-httpd-4
spec:
  type: LoadBalancer
  ports:
    - name: svc-httpd-4
      port: 80
      targetPort: 80
  selector:
    app: deploy-httpd-4
