apiVersion: v1
kind: Service
metadata:
  name: svc-httpd-5
  labels:
    app: svc-httpd-5
spec:
  type: LoadBalancer
  ports:
    - name: svc-httpd-5
      port: 80
      targetPort: 80
  selector:
    app: deploy-httpd-5                                
